# SPDX-FileCopyrightText: 2024 Julia DeMille <me@jdemille.com
#
# SPDX-License-Identifier: Parity-7.0.0

match_block_trailing_comma = true
max_width = 90
merge_derives = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true